### ISSUE TITLE
add page on using the DMPTool 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/dataWebsite#41]
placeholder at : https://bulib.github.io/dataWebsite/manage/dmptool/

**Comment by liapark** [comment]
![pattern 1-02](https://cloud.githubusercontent.com/assets/15038464/22337297/a353dfbe-e3b2-11e6-9da1-5492bfed98f9.jpg)

**Comment by tomhohenstein** [comment]
added it to the website
