### ISSUE TITLE
Design Adjustments on Guide Page

### ISSUE THREAD

**Issue by liapark** [bulib/dataWebsite#50]
Adjustment of center alignment (of the guide title boxes) need to be made according to the title at the top and the overall size of the page. Left section of boxes are slightly larger than the ones on the right, and gap between the two sections are not in the center (alignment problem stated before).

The dimension of the box on the right is the same with that of the left, but the actual box is smaller because the dimension of the right includes the gap dimensions.

**Comment by liapark** [comment]
Also, the order of the patterns need editing - purple, dark red, red, yellow, light green, dark green, to blue would be most ideal!

**Comment by liapark** [comment]
![guides adjustment](https://cloud.githubusercontent.com/assets/15038464/22759657/3939d614-ee21-11e6-895d-8dbd9144a536.jpg)


Some adjustments needed for the actual guide pages

**Comment by tomhohenstein** [comment]
I've updated the guide index layout so the section titles are now the same size.

**Comment by tomhohenstein** [comment]
updated the width of the article element to 625. let me know if this should be larger @liapark. 

Closing this for now

**Comment by liapark** [comment]
box alignment adjusting is needed (not centered)

**Comment by tomhohenstein** [comment]
fix css styles for article max-width (create a class)

**Comment by tomhohenstein** [comment]
done!
