### ISSUE TITLE
Create Data Citation Page 

### ISSUE THREAD

**Issue by tomhohenstein** [bulib/dataWebsite#6]
Create a page on data citation

**Comment by liapark** [comment]
![pattern 4 edited-01](https://cloud.githubusercontent.com/assets/15038464/22337215/779a7a54-e3b2-11e6-904c-16f4458e0a8c.jpg)

**Comment by tomhohenstein** [comment]
add it to the website  : )

**Comment by tomhohenstein** [comment]
@mbcheng - great suggestions. The page has been updated at: https://bulib.github.io/dataWebsite/manage/citing-data/

@jdkotula is going to add some additional content and edits. 

Moving forward ✈️

**Comment by tomhohenstein** [comment]
Done!
