### ISSUE TITLE
Editing suggestions on landing page

### ISSUE THREAD

**Issue by mbcheng** [bulib/dataWebsite#69]
+ misspelling of accessible 
+ In DMP Tool Box – "..like the National Science Foundation and the Sloan Foundation the DMPTool has the template you need to get started." – comma after Foundation
+ In DMP Tool Box, look over first sentence – says basically the say thing as the graphic above
+ On Campus should be On-Campus
+ Period after "Need help? Schedule a one-on-one consultation" in Consultations box
+ Write out IS&T on first reference

**Comment by tomhohenstein** [comment]
great finds! keep them coming
